### ISSUE TITLE
/bin/sh: 1: youtube-dl: not found

### ISSUE THREAD

**Issue by Borderpatrol1987** [dmzoneill/lidarr-youtube-downloader#14]
I have this running in docker, and its able to see my lidarr DB.

I get this message when it try's to download
/bin/sh: 1: youtube-dl: not found

How can I fix this?

**Comment by Borderpatrol1987** [comment]
That's resolved. but now it acts like its downloading the file, but its not  writing the files.

**Comment by dmzoneill** [comment]
can you provide console output

**Comment by guerda** [comment]
The ` yt-dlp` by default is called like this and not `youtube-dl`. Maybe it would be a good idea to update https://github.com/dmzoneill/lidarr-youtube-downloader/blob/c00c4c649742551a31055b081ef8054d4e3cfffa/lidarr_youtube_downloader/lyd.py#L407 to use the "official" binary name? Then the renaming of the binary can also be removed and it makes it easier to use it locally via `pip`.
