### ISSUE TITLE
usage

### ISSUE THREAD

**Issue by skijbal** [dmzoneill/lidarr-youtube-downloader#15]
Will this update lidarr with the current files?

**Comment by n0tOdd** [comment]
No i dont think so but this curl command almost works so it should not be to hard to implement i think

curl -s "192.168.86.96:8686/api/v1/command" --header "X-Api-Key:4a48ffd111be436e99304e5ab3747915" -H "Content-Type: application/json" --data "{\"name\":\"DownloadedAlbumsScan\", \"path\":\"Path to downloaded file"}"

**Comment by dmzoneill** [comment]
Sorry, you question is a little vague
