### ISSUE TITLE
Error Building using Dockerfile

### ISSUE THREAD

**Issue by Christoph-87** [dmzoneill/lidarr-youtube-downloader#24]
When I try to build the container using the Dockerfile I get the following error:

`13:41:15 Package python3 is not available, but is referred to by another package.
13:41:15 This may mean that the package is missing, has been obsoleted, or
13:41:15 is only available from another source
13:41:15 However the following packages replace it:
13:41:15   python3-dev
13:41:15 
13:41:15 Package python3-pip is not available, but is referred to by another package.
13:41:15 This may mean that the package is missing, has been obsoleted, or
13:41:15 is only available from another source
13:41:15 
13:41:15 
13:41:15 [91mE: Version '3.12.1-0ubuntu1' for 'python3' was not found
13:41:15 E: Version '23.3+dfsg-1' for 'python3-pip' was not found
13:41:15 [0m
13:41:17 ERROR: Build step failed with exception
13:41:17 com.github.dockerjava.api.exception.DockerClientException: Could not build image: The command '/bin/sh -c DEBIAN_FRONTEND=noninteractive apt-get update -y &&     DEBIAN_FRONTEND=noninteractive apt-get upgrade -y &&     DEBIAN_FRONTEND=noninteractive apt-get install  --no-install-recommends -y ffmpeg=7:6.1.1-1ubuntu1 python3=3.12.1-0ubuntu1 curl=8.5.0-2ubuntu2 python3-pip=23.3+dfsg-1 python-is-python3=3.11.4-1 &&     DEBIAN_FRONTEND=noninteractive apt-get clean &&     rm -r -f /var/lib/apt/lists/* &&     python3 -m pip install --no-cache-dir --break-system-packages  --no-deps -U yt-dlp==2024.2.25.232703.dev0 &&     pip3 install --no-cache-dir --break-system-packages requests==2.27.1 eyed3==0.9.7 youtube-search-python==1.6.6 typer==0.9.0' returned a non-zero code: 100
13:41:17 	at com.github.dockerjava.api.command.BuildImageResultCallback.getImageId(BuildImageResultCallback.java:78)
13:41:17 	at com.github.dockerjava.api.command.BuildImageResultCallback.awaitImageId(BuildImageResultCallback.java:50)
13:41:17 	at com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher$Run.buildImage(DockerBuilderPublisher.java:425)
13:41:17 	at com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher$Run.run(DockerBuilderPublisher.java:359)
13:41:17 	at com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher.perform(DockerBuilderPublisher.java:520)
13:41:17 	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
13:41:17 	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:80)
13:41:17 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
13:41:17 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:818)
13:41:17 	at hudson.model.Build$BuildExecution.build(Build.java:199)
13:41:17 	at hudson.model.Build$BuildExecution.doRun(Build.java:164)
13:41:17 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:526)
13:41:17 	at hudson.model.Run.execute(Run.java:1893)
13:41:17 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:44)
13:41:17 	at hudson.model.ResourceController.execute(ResourceController.java:101)
13:41:17 	at hudson.model.Executor.run(Executor.java:442)
13:41:17 Build step 'Build / Publish Docker Image' marked build as failure
13:41:17 Finished: FAILURE`

I guess the Dockerfile needs to be amended such that it is possible to use it?

**Comment by dmzoneill** [comment]
i pushed a fix, i dont really use docker for this solution.
apolgies for the inconvenience
