### ISSUE TITLE
download-only mode

### ISSUE THREAD

**Issue by Byter09** [dmzoneill/lidarr-youtube-downloader#6]
Hello!

This looks like the right tool for the job, however I noticed that it also requires direct access to the database, which I am wary about.

Out of curiosity, is there a way to have some kind of "download-only" mode, in which it gets a list of missing songs, downloads them and then just stores them in a folder for Lidarr to pick up itself? This would also help people that have multiple Lidarr instances for whatever reason. This would also make "correct paths" irrelevant, as one could just mount the download folder anywhere and have the user deal with the files themselves.

Thanks for taking the time to answer! :)

**Comment by dmzoneill** [comment]
you can probably cheat the behaviour quite easily.

```
cp /path/to/the/lidarr.db /tmp/break/this/if/you/want.db
export LIDARR_MUSIC_PATH=/tmp/break/this/if/you/want.db
lyd
```

if will start modifying the db copy you just made in /tmp
and the music will be stored in that folder you specified.
You can just into lidarr and tell it to import that directory you just made.

**Comment by Byter09** [comment]
Oh fascinating, I didn't even think of tricking it haha. Thanks!
