### ISSUE TITLE
Typer module error

### ISSUE THREAD

**Issue by IT-freak-Jake** [dmzoneill/lidarr-youtube-downloader#8]
Hi, after setting up my container with lyd and starting it I am getting this error and container crash:

Traceback (most recent call last):
  File "/lyd.py", line 17, in <module>
    import typer
ModuleNotFoundError: No module named 'typer'

I've tried adding "typer[all]" in Dockerfile in the line with pip3 install and that resulted in the container crashing without anything in the logs. If that changes anything I'm using Docker in Unraid

**Comment by TomCasavant** [comment]
That's one of the things I addressed in #9
